<a href="https://colab.research.google.com/github/pradeep-dani/pd-mt-iiitdh-colab/blob/main/L5_L6_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Working with Numpy Arrays**

In [1]:
#Creating a single dimension ndarray object
import numpy as np
a = np.array
print(a)

<built-in function array>


In [4]:
#Creating a two dimension ndarray object
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.ndim)
print(a.max(axis=0))
print(a.max(axis=1))

2
[4 5 6]
[3 6]


In [18]:
# Printing data type of array object
import numpy as np
a = np.array([[1,2,3],[2,300000000000000,4]])
b = "test";
print("Each item is of the type",a.dtype, a.argmax(axis=0))
print(">>>", b.upper())

Each item is of the type int64 [1 1 1]
>>> TEST


In [19]:

import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print("printing the original array..")
print(a)
a=a.reshape(2,3)
print("printing the reshaped array..")
print(a)

printing the original array..
[[1 2]
 [3 4]
 [5 6]]
printing the reshaped array..
[[1 2 3]
 [4 5 6]]


In [20]:
# Printing Attributes of ndarray object - dimensions, size, shape, data type and size
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print("Array axes (dimensions): ",a.ndim)
print("Array Size:",a.size)
print("Shape:",a.shape)
print("Data type of array elements:",a.dtype)
print("Size (in bytes) of each element: ",a.itemsize)

Array axes (dimensions):  2
Array Size: 6
Shape: (2, 3)
Data type of array elements: int64
Size (in bytes) of each element:  8


In [ ]:
# Reshaping the array objects
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print("printing the original array..")
print(a)
a=a.reshape(2,3)
print("printing the reshaped array..")
print(a)

printing the original array..
[[1 2]
 [3 4]
 [5 6]]
printing the reshaped array..
[[1 2 3]
 [4 5 6]]


In [ ]:
# Slicing in the Array
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
print(a[0,1])
print(a[2,0])

2
5


In [ ]:
# The linspace() function returns the evenly spaced values over the given interval.
# The following example returns the 10 evenly separated values over the given interval 5-15
import numpy as np
a=np.linspace(50,100,10)
print(a)

[ 50.          55.55555556  61.11111111  66.66666667  72.22222222
  77.77777778  83.33333333  88.88888889  94.44444444 100.        ]


In [ ]:
# Finding the maximum, minimum, and sum of the array elements
import numpy as np
a=np.array([10,20,30,100,150,400])
print("The array:",a)
print("The maximum element:",a.max())
print("The minimum element:",a.min())
print("The sum of the elements:",a.sum())

The array: [ 10  20  30 100 150 400]
The maximum element: 400
The minimum element: 10
The sum of the elements: 710


In [ ]:
# NumPy Array Axis
import numpy as np
a = np.array([[10,20,30],[40,50,60]])
print("The array:\n",a)
print("The maximum elements of rows:",a.max(axis = 1))
print("The minimum element of rows",a.min(axis = 1))
print("The sum of all rows",a.sum(axis = 1))

The array:
 [[10 20 30]
 [40 50 60]]
The maximum elements of rows: [30 60]
The minimum element of rows [10 40]
The sum of all rows [ 60 150]


In [ ]:
# Finding square root and standard Deviation
import numpy as np
a = np.array([[1,2,30],[10,15,4]])
print(np.sqrt(a))
print(np.std(a))

[[1.         1.41421356 5.47722558]
 [3.16227766 3.87298335 2.        ]]
10.044346115546242


In [ ]:
# Arithmetic operations on the array
import numpy as np
a = np.array([[1,2,30],[10,15,4]])
b = np.array([[1,2,3],[12, 19, 29]])
print("Sum of array a and b\n",a+b)
print("Product of array a and b\n",a*b)
print("Division of array a and b\n",a/b)

Sum of array a and b
 [[ 2  4 33]
 [22 34 33]]
Product of array a and b
 [[  1   4  90]
 [120 285 116]]
Division of array a and b
 [[ 1.          1.         10.        ]
 [ 0.83333333  0.78947368  0.13793103]]


In [ ]:
# Array Concatenation - vertical stacking and horizontal stacking
import numpy as np
a = np.array([[1,2,30],[10,15,4]])
b = np.array([[1,2,3],[12, 19, 29]])
print("Arrays vertically concatenated\n",np.vstack((a,b)));
print("Arrays horizontally concatenated\n",np.hstack((a,b)))

Arrays vertically concatenated
 [[ 1  2 30]
 [10 15  4]
 [ 1  2  3]
 [12 19 29]]
Arrays horizontally concatenated
 [[ 1  2 30  1  2  3]
 [10 15  4 12 19 29]]


In [ ]:
# Creating an array with unspecified contents
import numpy as np
arr = np.empty((3,2), dtype = int)
print(arr)

[[4607182418800017408 4607182418800017408]
 [4621819117588971520 4605681218924227243]
 [4605286166325335094 4594137509534530454]]


In [ ]:
# Creating an array with all zero elements
import numpy as np
arr = np.zeros((3,2), dtype = int)
print(arr)

[[0 0]
 [0 0]
 [0 0]]


In [ ]:
# Creating an array with all elements as ones
import numpy as np
arr = np.ones((3,2), dtype = int)
print(arr)

[[1 1]
 [1 1]
 [1 1]]


In [ ]:
# creating Numpy Array from Existing Data - list
#Creating numpy array using the list
import numpy as np
l=[1,2,3,4,5,6,7]
a = np.asarray(l);
print(a)

[1 2 3 4 5 6 7]


In [ ]:
# creating Numpy Array from Existing Data - tuple
#Creating a numpy array using Tuple
import numpy as np
l=(1,2,3,4,5,6,7)
a = np.asarray(l)
print(a)

[1 2 3 4 5 6 7]


In [ ]:
# creating Numpy Arrays within the numerical range
# Numpy.arrange
# numpy.arrange(start, stop, step, dtype)
import numpy as np
arr = np.arange(0,10,2,float)
print(arr)

[0. 2. 4. 6. 8.]


In [ ]:
# NumPy Broadcasting - perform operations where the array of different shapes are involved.
# For example, if we consider the matrix multiplication operation,
# if the shape of the two matrices is the same then this operation will be easily performed
import numpy as np
a = np.array([1,2,3,4,5,6,7])
b = np.array([2,4,6,8,10,12,14])
c = a*b;
print(c)

[ 2  8 18 32 50 72 98]


In [ ]:
# If we consider arrays of different shapes, we will get the errors as shown below.
# the first array has 7 elements and second array has 8 elements
import numpy as np
a = np.array([1,2,3,4,5,6,7])
b = np.array([2,4,6,8,10,12,14,19])
c = a*b;
print(c)

ValueError: operands could not be broadcast together with shapes (7,) (8,) 

In [ ]:
# perform addition of arrays of different sizes
import numpy as np
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])
b = np.array([2,4,6,8])
print("\nprinting array a..")
print(a)
print("\nprinting array b..")
print(b)
print("\nAdding arrays a and b ..")
c = a + b;
print(c)


printing array a..
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

printing array b..
[2 4 6 8]

Adding arrays a and b ..
[[ 3  6  9 12]
 [ 4  8 11 14]
 [12 24 45 11]]


In [ ]:
# Numpy String functions - numpy.char.add() method example
import numpy as np
print("Concatenating two string arrays:")
print(np.char.add(['welcome','Hi,'], [' to IIIT Dharwad', ' Practice'] ))

Concatenating two string arrays:
['welcome to IIIT Dharwad' 'Hi, Practice']


In [ ]:
# Numpy String functions - numpy.char.multiply() method example
import numpy as np
print("Printing a string multiple times:")
print(np.char.multiply("iiitdh ",3))

Printing a string multiple times:
iiitdh iiitdh iiitdh 


Here's a step-by-step explanation:

Import numpy: Imports the numpy library.
Print descriptive text: Prints a message indicating what the code is about to do.
Capitalize the string: Uses np.char.capitalize("welcome to iiit dharwad") to take the input string "welcome to iiit dharwad" and return a new string with the first letter capitalized ("Welcome to iiit dharwad").
Print the result: Displays the capitalized string.**bold text** **bold text**

In [ ]:
# Numpy String functions - numpy.char.capitalize() method example
import numpy as np
print("Capitalizing the string using capitalize()...")
print(np.char.capitalize("welcome to iiit dharwad"))

Capitalizing the string using capitalize()...
Welcome to iiit dharwad


In [ ]:
# Numpy String functions - numpy.char.split() method example
import numpy as np
print("Splitting the String word by word..")
print(np.char.split("Welcome to IIIT Dharwad"),sep = " ")

Splitting the String word by word..
['Welcome', 'to', 'IIIT', 'Dharwad']


In [ ]:
# Numpy Statistical Functions - to perform statistical analysis
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n",a)
print("\nMedian of array along axis 0:",np.median(a,0))
print("Mean of array along axis 0:",np.mean(a,0))
print("Average of array along axis 1:",np.average(a,1))

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Median of array along axis 0: [4. 5. 6.]
Mean of array along axis 0: [4. 5. 6.]
Average of array along axis 1: [2. 5. 8.]


In [ ]:
# NumPy Sorting and Searching
import numpy as np
a = np.array([[10,2,3],[4,5,6],[7,8,9]])
print("The given array")
print(a)
print("Sorting along the columns:")
print(np.sort(a))
print("Sorting along the columns:")
print(np.sort(a, 0))
data_type = np.dtype([('name', 'S15'),('marks',int)])
arr = np.array([('Rakesh',89),('Mary',95)],dtype = data_type)
print("Sorting data ordered by name")
print(np.sort(arr,order = 'name'))
print("Sorting data ordered by marks")
print(np.sort(arr,order = 'marks'))

The given array
[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]
Sorting along the columns:
[[ 2  3 10]
 [ 4  5  6]
 [ 7  8  9]]
Sorting along the columns:
[[ 4  2  3]
 [ 7  5  6]
 [10  8  9]]
Sorting data ordered by name
[(b'Mary', 95) (b'Rakesh', 89)]
Sorting data ordered by marks
[(b'Rakesh', 89) (b'Mary', 95)]


In [ ]:
#Example: Aggregation
import numpy as np
data = np.array([[1, 2, 3],
                 [4, 5, 6]])

print(data.sum())       # total
print(data.sum(axis=0)) # column sums
print(data.mean(axis=1))# row means

21
[5 7 9]
[2. 5.]


In [ ]:
#Broadcasting - Allows operations on arrays of different shapes
# Useful in data transformations and simulations
a = np.array([1, 2, 3])
b = 2
print(a * b)   # [2 4 6]

[2 4 6]


In [ ]:
# Monte Carlo Simulations
# Example: π Estimation
import numpy as np
N = 1_000_000
rng = np.random.default_rng(42)

x, y = rng.random(N), rng.random(N)
inside = (x**2 + y**2) <= 1

pi_est = 4 * inside.mean()
print("π ≈", pi_est)

π ≈ 3.142436


In [ ]:
# Monte Carlo Simulations
# Example: Random Walk
steps = rng.integers(0, 2, size=1000) * 2 - 1
position = np.cumsum(steps)

print("Final position:", position[-1])

Final position: -4


In [ ]:
# Hands-on Activities

In [26]:
# 1. Compute row/column means for a random 5×5 matrix
import numpy as np

# Create a random 5x5 matrix (values between 0 and 1)
rng = np.random.default_rng(1)  # reproducible results
matrix = rng.random((5, 5))

print("Matrix:\n", matrix)

# Row means (axis=1 → across columns)
row_means = matrix.mean(axis=1)

# Column means (axis=0 → across rows)
col_means = matrix.mean(axis=0)

print("\nRow means:", row_means)
print("Column means:", col_means)

Matrix:
 [[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145]
 [0.42332645 0.82770259 0.40919914 0.54959369 0.02755911]
 [0.75351311 0.53814331 0.32973172 0.7884287  0.30319483]
 [0.45349789 0.1340417  0.40311299 0.20345524 0.26231334]
 [0.75036467 0.28040876 0.48519097 0.9807372  0.96165719]]

Row means: [0.57338517 0.4474762  0.54260233 0.29128423 0.69167176]
Column means: [0.57850475 0.54615201 0.35427889 0.69417286 0.37331119]


In [27]:
# 2. Simulate 10,000 coin flips → fraction of heads
# Simulate 10,000 coin flips (0 = Tails, 1 = Heads)
flips = rng.integers(0, 2, size=10_000)

# Compute fraction of heads
fraction_heads = flips.mean()

print("Fraction of Heads:", fraction_heads)

Fraction of Heads: 0.5007


In [21]:
# 3. Run a random walk and plot positions
import matplotlib.pyplot as plt

# Number of steps in the walk
n_steps = 1000

# Steps are ±1 with equal probability
steps = rng.integers(0, 2, size=n_steps) * 2 - 1

# Position is the cumulative sum of steps
position = np.cumsum(steps)

# Plot the random walk
plt.figure(figsize=(8,4))
plt.plot(position, lw=1)
plt.title("1D Random Walk")
plt.xlabel("Step")
plt.ylabel("Position")
plt.grid(True)
plt.show()

ModuleNotFoundError: No module named 'matplotlib'