<a href="https://colab.research.google.com/github/pradeep-dani/pd-mt-iiitdh-colab/blob/main/DS%20Lab%20Assignments/DS_Lab_Assignment_2_25_10_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
#Question 1 — Broadcasting and Indexing

#Given
import numpy as np
arr = np.array([[2, 4, 6],
                [8, 10, 12],
                [14, 16, 18]])

#ask 1: Use slicing to extract the second and third columns.
arr_secondCol = arr[:,1];
arr_thirdCol = arr[:,2];
print("Second Col as Array", arr_secondCol);
print("Third Col as Array", arr_thirdCol);
print("\n");
#ask 2: Use braodcasting and add the given array [1, 2, 3]
arr_toBeAdded = np.array([1,2,3])

print("Given Array A \n", arr)
print("Given Array B \n", arr_toBeAdded)
arr_broadcasted = arr + arr_toBeAdded;
print("\nBroadcasted Array (A+B) \n", arr_broadcasted);

#ask 3: Explain the broad casting
# When M X N matrix is given,
# addition will be possible if the array is of size 1 X N or M X 1

# A is matrix such as Aij (i index of row, j index of column)
# B is matrix such as Bij (i index of row, j index of column

# Adition can be done with following
# such that a11 + b11, a12 + b12 , a13 + b13
#           a21 + b21, a22 + b22 , a23 + b23
#           a31 + b31, a32 + b32 , a33 + b33


Second Col as Array [ 4 10 16]
Third Col as Array [ 6 12 18]


Given Array A 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Given Array B 
 [1 2 3]

Broadcasted Array (A+B) 
 [[ 3  6  9]
 [ 9 12 15]
 [15 18 21]]


In [33]:
#Question 2 — Random and Statistical Functions

#Create a 4×4 array of random integers between 10 and 50 (inclusive).
arr_4x4 = np.random.randint(10, 51, size=(4, 4))
print("Create a 4×4 array of random integers between 10 and 50 (inclusive)")
print(arr_4x4)


#Find the mean, standard deviation, and maximum of the array.
print("\nFind the mean, standard deviation, and maximum of the array.");
arr_4x4_mean = np.mean(arr_4x4)
arr_4x4_std = np.std(arr_4x4)
arr_4x4_max = np.max(arr_4x4)
print("1. mean =", arr_4x4_mean);
print("2. standard deviation =", arr_4x4_std);
print("3. maximum of the array =", arr_4x4_max);

#Replace all elements greater than the mean with 0.
print("\nReplace all elements greater than the mean with 0.")
print("Given Array\n", arr_4x4);
arr_4x4[arr_4x4 > arr_4x4_mean] = 0
print("Result Array\n", arr_4x4);


#


Create a 4×4 array of random integers between 10 and 50 (inclusive)
[[49 14 46 33]
 [31 15 44 24]
 [15 14 16 50]
 [41 11 10 11]]

Find the mean, standard deviation, and maximum of the array.
1. mean = 26.5
2. standard deviation = 14.713938969562161
3. maximum of the array = 50

Replace all elements greater than the mean with 0.
Given Array
 [[49 14 46 33]
 [31 15 44 24]
 [15 14 16 50]
 [41 11 10 11]]
Result Array
 [[ 0 14  0  0]
 [ 0 15  0 24]
 [15 14 16  0]
 [ 0 11 10 11]]


In [40]:
#Question 3 — Matrix Operations , Given the matrix:
A = np.array([[4, 2], [3, 5]])

# Compute the transpose and inverse of A.
print("Transpose of A\n", np.transpose(A));
print("Inverse of A\n", np.linalg.inv(A));

# Verify that the product of A and its inverse gives an identity matrix (within rounding error).
A_dot = np.dot(A, np.linalg.inv(A));
A_dot = np.round(A_dot, 2)
print("Product of A and its inverse is indeed identity matrix\n", A_dot);

#Explain why np.dot() is preferred over the * operator for matrix multiplication.
#lets do * operator and see whther it satisfy the formula A . A^-1 = I

A_cross = A * np.linalg.inv(A);
A_cross = np.round(A_cross, 2)
print("Product of A and its inverse is provides different matrix\n", A_cross);


# matrix multiplication is simple multiplying each element index (i,j) from matrix A to matrix B.
# (a11 * b11)  (a12 * b21)
# (a21 * b11)  (a22 * b21)

# Where as dot product is goes as follows , A(i,j) & B (i,j) of size mXn
# (a11*b11 + a12+b21) (a11*b12 + a12+b22)
# (a21*b11 + a22+b21) (a21*b12 + a22+b22

Transpose of A
 [[4 3]
 [2 5]]
Inverse of A
 [[ 0.35714286 -0.14285714]
 [-0.21428571  0.28571429]]
Product of A and its inverse is indeed identity matrix
 [[1. 0.]
 [0. 1.]]
Product of A and its inverse is provides different matrix
 [[ 1.43 -0.29]
 [-0.64  1.43]]


In [46]:
# Question 4 — linspace, reshape, and Slicing
# Create an array of 15 evenly spaced values between 0 and 30 using np.linspace().
print("Array of 15 evenly spaced values between 0 and 30 using np.linspace(). ")
arr_15 = np.linspace(0, 30, 15)
print(arr_15)

arr_15_reshape = arr_15.reshape(3,5)
print("\nReshape the array into a 3x5 matrix. ")
print(arr_15_reshape)

#-Extract the last two rows and the first three columns from the reshaped array.
print("\nExtract the last two rows and the first three columns from the reshaped array. ")
arr_15_reshape_extract = arr_15_reshape[1:, :3]
print(arr_15_reshape_extract)

#Compute the column-wise mean of this subarray.
print("\nCompute the column-wise mean of this subarray. ")
print(np.mean(arr_15_reshape_extract, axis=0))



Array of 15 evenly spaced values between 0 and 30 using np.linspace(). 
[ 0.          2.14285714  4.28571429  6.42857143  8.57142857 10.71428571
 12.85714286 15.         17.14285714 19.28571429 21.42857143 23.57142857
 25.71428571 27.85714286 30.        ]

Reshape the array into a 3x5 matrix. 
[[ 0.          2.14285714  4.28571429  6.42857143  8.57142857]
 [10.71428571 12.85714286 15.         17.14285714 19.28571429]
 [21.42857143 23.57142857 25.71428571 27.85714286 30.        ]]

Extract the last two rows and the first three columns from the reshaped array. 
[[10.71428571 12.85714286 15.        ]
 [21.42857143 23.57142857 25.71428571]]

Compute the column-wise mean of this subarray. 
[16.07142857 18.21428571 20.35714286]
